services:
  - type: web
    name: mind-ai-backend
    repo: https://github.com/Vaishnav00521/MIND-AI-mood-tracker-platform
    branch: main
    rootDirectory: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend_core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DJANGO_SETTINGS_MODULE
        value: "backend_core.settings"
    plan: free