# Generated by Django 6.0.3 on 2026-03-12 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mood_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moodresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='moodresult',
            index=models.Index(fields=['user', 'date'], name='mood_engine_user_id_64137b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moodresult',
            unique_together={('user', 'date')},
        ),
    ]
