# Generated by Django 6.0.3 on 2026-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='depression_risk_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_b2b_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('THERAPIST', 'Therapist'), ('ADMIN', 'Admin')], default='PATIENT', max_length=20),
        ),
    ]
